// Package swagger holds the OpenAPI (Swagger 2.0) definitions generated by
// `make swagger` and served by the inventory API at /swagger/*.
//
// The general API info (title, version, host, base path, security scheme) is
// annotated on func main in cmd/server/main.go; handler route annotations live
// in each package's handler.go. `swag init -g cmd/server/main.go -o
// docs/swagger` regenerates this package without manual edits.
package swagger
